# -*- coding: utf-8 -*-
"""2.2월.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Si7UJgP6n5xMzuwxlLmYYQsB4839krPk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!apt-get update -qq
!apt-get install fonts-nanum -qq

import matplotlib.font_manager as fm
fm._load_fontmanager(try_read_cache=False)

plt.rc('font', family = 'NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

print("환경 설정 완료")

tips = sns.load_dataset('tips')

tips.head(10)

tips.info()

tips.columns.tolist()

tips_kr = tips.copy()
tips_kr.columns = ['총액', '팁', '성별', '흡연여부', '요일', '시간대', '인원']

tips_kr.head()

tips_kr.info()

"""박스플롯
- 중앙값, 사분위 범위, 이상치
- 그룹 간 비교, 이상치 탐지에 효과적이다.
"""

#요일별 팁
plt.figure(figsize=(10, 6))
plt.boxplot(tips['tip'])

plt.title('팁 금액 분포(Boxplot)')
plt.ylabel('팁($)')

plt.show()

plt.figure(figsize=(10, 6))
plt.boxplot([tips_kr[tips_kr['요일'] == day]['팁'] for day in ['Thur', 'Fri', 'Sat', 'Sun']], tick_labels=['목요일', '금요일', '토요일', '일요일'])

plt.title('요일별 팁 금액 분포(Boxplot)', fontsize = 16, fontweight = 'bold')

plt.xlabel('요일', fontsize = 12)
plt.ylabel('팁($)', fontsize = 12)
plt.grid(True, alpha= 0.3, axis = 'y')


plt.show()

"""바이올린 그래프
- 밀도형태도 표현
"""

plt.figure(figsize=(10, 6))
sns.violinplot(y=tips['tip'])

plt.title('팁 금액 분포(Violin Plot)')
plt.ylabel('팁($)')

plt.show()

# 점심/ 저녁에 따른 식사 총액
tips_kr['시간대_kr'] = tips_kr['시간대'].map({'Lunch': '점심', 'Dinner': '저녁'})

plt.figure(figsize=(10, 6))

sns.violinplot(data = tips_kr, x='시간대_kr', y='총액', hue='시간대_kr', palette='Set2')
plt.title('시간대별 식사 총액 분포(Violin Plot)', fontsize = 16, fontweight = 'bold')
plt.xlabel('시간대', fontsize = 12)
plt.ylabel('총액($)', fontsize = 12)

plt.show()

"""히스토그램
- 분포, 치우침
- 평균과 중앙값을 수직선으로 함께 표시
"""

plt.figure(figsize=(10, 6))
plt.hist(tips['tip'], bins=10)

plt.title('팁 금액 분포(Histogram)')
plt.xlabel('팁($)')
plt.ylabel('빈도')

plt.show()

plt.figure(figsize=(10, 6))
plt.hist(tips_kr['팁'], bins=20, color='skyblue', edgecolor='black', alpha=0.7)

plt.axvline(tips_kr['팁'].mean(), color='red', linestyle='--', linewidth = 2, label=f'평균: ${tips_kr['팁'].mean():.2f}') # 평균값

plt.axvline(tips_kr['팁'].median(), color='green', linestyle='--', linewidth = 2, label=f'중앙값: ${tips_kr['팁'].median():.2f}') # 중앙값

plt.title('팁 금액 분포(Histogram)', fontsize = 16, fontweight = 'bold')
plt.xlabel('팁($)', fontsize = 12)
plt.ylabel('빈도', fontsize = 12)


plt.legend(fontsize = 11)
plt.grid(True, alpha= 0.3, axis = 'y')

plt.tight_layout()
plt.show()

"""평균값은 3, 과 중앙값이 조금 낮음.

일부의 고액 팁으로 인해 평균값을 늘리기 때문.

2-4 달러로 집중되어 분포

양의 왜도 분포 형태
"""

fig, axes = plt.subplots(1, 3, figsize=(15,4))

axes[0].boxplot([tips_kr[tips_kr['요일'] == day]['팁'] for day in ['Thur', 'Fri', 'Sat', 'Sun']], tick_labels=['목요일', '금요일', '토요일', '일요일'])
axes[0].set_title('요일별 팁 금액 분포(Boxplot)', fontsize = 16, fontweight = 'bold')
axes[0].set_xlabel('요일')
axes[0].set_ylabel('팁($)')
axes[0].grid(True, alpha= 0.3, axis = 'y')

sns.violinplot(data = tips_kr, x='시간대_kr', y='총액', hue='시간대_kr', palette='Set2', ax=axes[1])
axes[1].set_title('시간대별 식사 총액 분포(Violin Plot)', fontsize = 16, fontweight = 'bold')
axes[1].set_xlabel('시간대')
axes[1].set_ylabel('총액($)')

axes[2].hist(tips_kr['팁'], bins=20, color='skyblue', edgecolor='black', alpha=0.7)
axes[2].axvline(tips_kr['팁'].mean(), color='red', linestyle='--', linewidth = 2)
axes[2].set_title('팁 금액 분포(Histogram)', fontsize = 16, fontweight = 'bold')
axes[2].set_xlabel('팁($)')
axes[2].set_ylabel('빈도')
axes[2].grid(True, alpha= 0.3, axis = 'y')

plt.suptitle('팁 데이터 종합 분석 대시보드', fontsize = 18, fontweight = 'bold', y=1.02)
plt.tight_layout()
plt.show()

"""박스플릇- 비교 중심

바이올린- 분포 형태

히스토그램- 전체 빈도 구조
"""

print(f"팁 금액 통계:")
print(f"평균: ${tips_kr['팁'].mean():.2f}")
print(f"중앙값: ${tips_kr['팁'].median():.2f}")
print(f"최솟값: ${tips_kr['팁'].min():.2f}")
print(f"최댓값: ${tips_kr['팁'].max():.2f}")
print(f"표준편차: ${tips_kr['팁'].std():.2f}")

print(f"요일별 평균 팁")
for day, day_kr in zip(['Thur', 'Fri', 'Sat', 'Sun'], ['목요일', '금요일', '토요일', '일요일']):
  avg_tip = tips_kr[tips_kr['요일'] == day]['팁'].mean()
  print(f"{day_kr}: ${avg_tip:.2f}")

print(f"시간대별 평균 팁")
for time in tips_kr['시간대_kr'].unique():
  avg_tip = tips_kr[tips_kr['시간대_kr'] == time]['팁'].mean()
  print(f"{time}: ${avg_tip:.2f}")

"""이상치 탐지 (IQR 방법)
- 이상치를 실체 데이터 값으로 확인
- Q3-Q1
"""

Q1 = tips_kr['팁'].quantile(0.25)
Q3 = tips_kr['팁'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = tips_kr[(tips_kr['팁'] < lower_bound) | (tips_kr['팁'] > upper_bound)]

print(f"IQR 기준 이상치:")
print(f"정상범위: ${lower_bound:.2f} ~ ${upper_bound:.2f}")
print(f"이상치 개수:{len(outliers)}개")
if len(outliers) > 0:
  print(f"이상치 값:{outliers['팁'].values}")

"""이상치는 대부분 큰 값.


분석목적에 따라 이상값을 제거할지, 유지할지 선택.

상관관계 시각화를 통한 변수 간 관계 분석 코드 설명
- 히트맵
- 산점도
"""

# 식사 총액, 팁, 인원수 간의 관계를 분석
tips_numeric = tips[['total_bill', 'tip', 'size']]
tips_numeric.columns = ['총액', '팁', '인원']

tips_numeric.head()

# 상관계수 행렬 계산
correlation_matrix = tips_numeric.corr()

correlation_matrix

"""[히트맵]
- 색이 진할수록 상관관계가 깊음.
- 상관관계 시각화
"""

# 히트맵
plt.figure(figsize=(10,6))
sns.heatmap(correlation_matrix)

plt. title('변수 간 상관관계 히트맵')

plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(correlation_matrix,
            annot=True,
            fmt='.2f',
            cmap='coolwarm',
            vmin=-1, vmax=1,
            center=0,
            square=True,
            linewidths=1,
            cbar_kws={'shrink': 0.8})

plt. title('변수 간 상관관계 히트맵', fontsize = 16, fontweight = 'bold')

plt.show()

# 산점도 (선형 회귀선을 추가, 상관계수 표시)
# 총액과 팁의 관계(산점도)

plt.figure(figsize=(10,6))
sns.scatterplot(x=tips_numeric['총액'], y=tips_numeric['팁'])

z = np.polyfit(tips_numeric['총액'], tips_numeric['팁'], 1)
p = np.poly1d(z)
plt.plot(tips_numeric['총액'], p(tips_numeric['총액']), 'r--', linewidth=2, label=f'추세선: y={z[0]:.2f}x+{z[1]:.2f}')

corr = tips_numeric['총액'].corr(tips_numeric['팁'])
plt.text(0.05, 0.95, f'상관계수: {corr:.3f}', transform=plt.gca().transAxes, fontsize=14, verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

plt.title('총액과 팁의 관계(산점도)', fontsize = 16, fontweight = 'bold')
plt.xlabel('총액($)')
plt.ylabel('팁($)')
plt.legend()
plt.grid(True, alpha= 0.3)

plt.tight_layout()
plt.show()

#인원과 총액의 관계(산점도), 팁의 크기
plt.figure(figsize=(10,6))
plt.scatter(tips_numeric['인원'], tips_numeric['총액'],
            s=tips_numeric['팁']*20,
            alpha=0.5, c=tips_numeric['팁'], cmap='YlOrRd', edgecolors='black')

plt.colorbar(label='팁($)')

corr2 = tips_numeric['인원'].corr(tips_numeric['총액'])
plt.text(0.05, 0.95, f'상관계수: {corr2:.3f}',
         transform=plt.gca().transAxes,
         fontsize=14, verticalalignment='top',
         bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

plt.title('인원과 총액의 관계(산점도)', fontsize = 16, fontweight = 'bold')
plt.xlabel('인원(명)', fontsize = 12)
plt.ylabel('총액($)', fontsize = 12)
plt.legend()
plt.grid(True, alpha= 0.3)

plt.tight_layout()
plt.show()

"""종합 비교

범주형 변수 활용 (색상 구분) Mask[tips]
"""

